
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 15 01:59:52 BOT 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_Logical = 17;
  public static final int Divide = 15;
  public static final int LParen = 8;
  public static final int SEMICOLON = 20;
  public static final int Numero = 22;
  public static final int LCurly = 10;
  public static final int Assign = 19;
  public static final int ERROR = 21;
  public static final int Memb_Access = 18;
  public static final int Op_Booleano = 7;
  public static final int Identificador = 23;
  public static final int Int = 3;
  public static final int Minus = 13;
  public static final int Print = 6;
  public static final int Sum = 12;
  public static final int Multiply = 14;
  public static final int EOF = 0;
  public static final int Power = 16;
  public static final int If = 4;
  public static final int Return = 5;
  public static final int error = 1;
  public static final int Class = 2;
  public static final int RParen = 9;
  public static final int RCurly = 11;
}

